### ISSUE TITLE
any logged in user can manage projects

### ISSUE THREAD

**Issue by vinyll** [etalab/piaf#10]
once logged in, accessing `/project/` permits to delete, edit or create a new project.
This feature should be limited to admin users only.

**Comment by guillim** [comment]
This permission doesn't satisfy this ?

![Screen Shot 2019-09-30 at 16 56 20](https://user-images.githubusercontent.com/13087916/65890520-4ba83500-e3a3-11e9-8a2d-7c8f2041160e.png)

**Comment by vinyll** [comment]
Good point, I didn't notice that one! 🏅 

We do get a `403 Forbidden` when accessing as non admin.
