### ISSUE TITLE
GPDR compliance

### ISSUE THREAD

**Issue by vinyll** [etalab/piaf#11]
We are leaking data to Google and may end up storing identification cookie and authentication.
We must be GPDR compliant.

**Comment by guillim** [comment]
Where are we doing it ?

**Comment by vinyll** [comment]
As [we are using Google Analytics](https://github.com/etalab/piaf/blob/b305d3ccbf4a7c562f4c352bc4fd82976b3ecbca/app/server/templates/tags/google_analytics.html#L3) they collect data.

Usage cookies might be in the future for storing when a visitor has seen the tour if we do one.

Authentication cookies are generated by Django for saving the referencee of the session that a visitor has when he authenticated.

**Comment by guillim** [comment]
True, i just checked it in your PR

**Comment by guillim** [comment]
we don't use GA any longer
