### ISSUE TITLE
Prod 500 if DEBUG=False

### ISSUE THREAD

**Issue by guillim** [etalab/piaf#14]
If, in docker-compose.yml we set DEBUG=True, we end up with an error 500. 

![Screen Shot 2019-10-01 at 19 16 16](https://user-images.githubusercontent.com/13087916/65984388-f857e480-e47f-11e9-902e-e0f921cc169b.png)

**Comment by vinyll** [comment]
Oh funny. What is you set `DEBUG: 1`?

**Comment by VladOsiichuk** [comment]
Can I take care of this issue?

**Comment by VladOsiichuk** [comment]
Hi @vinyll! Could you tell me where you face with 500 error? maybe it is some specific page? or project even can`t start? I have just started project locally and did not notice any errors.

**Comment by vinyll** [comment]
Hey @VladOsiichuk, I haven't investigated yet on this task.
@guillim runs with `docker-compose` and has the issue.
I run with Django's `runserver` and it works.

However I experiment the following in the logs running ` DEBUG=0 python src/manage.py runserver` and `tail -f src/debug.log` aside:

```
"GET /projects/1/ HTTP/1.1" 500 59
"GET /v1/projects/1/labels HTTP/1.1" 500 59
"GET /v1/me HTTP/1.1" 500 59
"GET /v1/projects/1 HTTP/1.1" 500 59
"GET /favicon.ico HTTP/1.1" 500 59
"GET /v1/projects/1/docs?q=&is_checked=&offset=0&seq2seq_annotations__isnull=true HTTP/1.1" 500 59
"GET /v1/projects/1/statistics HTTP/1.1" 500 59
```
Any idea on your end? 🤔

**Comment by VladOsiichuk** [comment]
No any idea :( I can't reproduce these errors. Project starts successfully with DEBUG="True" in docker-compose. Maybe you can give me environment variables with which you start docker-compose?
I know the reason why "GET /v1/projects/1 HTTP/1.1" 500 59 does not work. You have not implemented property "image" in the Project class. The next following errors are related to unimplemented methods/properties too. I can help if you tell me what these methods/properties should return. Could you also add "hacktoberfest" label to these issues?
 
"GET /v1/projects/1/docs?q=&is_checked=&offset=0&seq2seq_annotations__isnull=true HTTP/1.1" 500 59
"GET /v1/projects/1/statistics HTTP/1.1" 500 59

**Comment by guillim** [comment]
@VladOsiichuk My apologies. I tried to reproduce the Bug, and I failed. It is because the bug appears for DEBUG=False, and not when DEBUG=True. Sorry about that. Do you want to investigate ?

![Screen Shot 2019-10-08 at 11 16 39](https://user-images.githubusercontent.com/13087916/66383467-570be980-e9bd-11e9-8fa7-20cb25fad2e5.png)


![Screen Shot 2019-10-08 at 11 16 31](https://user-images.githubusercontent.com/13087916/66383476-5c693400-e9bd-11e9-9490-a9d0762918f4.png)

**Comment by guillim** [comment]
(I updated the title of the issue)

**Comment by guillim** [comment]
no time, no updates. closing.

feel free to re-open later on
