### ISSUE TITLE
Bug UI surlignage desktop au niveau de la croix

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/piaf#19]
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36

![](https://puu.sh/EwMl1/2dae1344a0.png)

**Comment by guillim** [comment]
Normalement ce problème devrait être résolu
