### ISSUE TITLE
Contraste, légibilité, facilité de lecture

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/piaf#21]
Actuellement, la police est très fine, a une taille très petite et les couleurs ne facilitent pas l'utilisation prolongée de l'application.

![](https://puu.sh/EwMvm/37a518d351.png)

Pour utiliser l'application, j'utilise personnellement un niveau de zoom de 150% sur un ordinateur.

**Comment by guillim** [comment]
✅
