### ISSUE TITLE
Format json pour l'importation de texte

### ISSUE THREAD

**Issue by ThomasNaimePloyon** [etalab/piaf#23]
Bonjour,

Lorsque j'essaye d'importer des textes via l'interface, j'ai un problème concernant le format du json. J'ai la version de squad ainsi que displaytitle, categorie et paragraph à l’intérieur de mon Json mais j'obtiens une erreur concernant le champ reference j'ai essayé de le renseigner avec une id wikipedia mais ça ne change pas l'erreur.
J'aimerais savoir qu'elle est la structure attendue du Json pour l'importation de texte et qu'elle est exactement le rôle du champ reference.

**Comment by guillim** [comment]
I pushed a small update on the repo. let me know if you still encounter your issue. if you do, make sure _reference_ is an integer (or remove it). Also attach here a sample of your JSON so that I can tell what may be causing this issue
