### ISSUE TITLE
Template not found and other installation issues

### ISSUE THREAD

**Issue by oersoy1** [etalab/piaf#25]
Carrying over from the Doccano repo. I cannot run the Annotation tool. It gives me a Template not found error. I tried it with both the docker and without. Installation completes but with errors. 

System: MacOs Mojave 10.14
Python: 3.7.6
Django: 3.0.7
Node.js: 12.18.0

Without Docker installation gives this error:
`ERROR: mixer 6.1.3 has requirement Faker==0.9.1, but you'll have faker 0.8.8 which is incompatible.`

Then the 
`make build-statics`
Returns this error:

```
cd src/piaf/front/static && npm run build
/bin/sh: line 0: cd: src/piaf/front/static: No such file or directory
make: *** [build-statics] Error 1
```

If I run the `npm run build` manually where the package.json is via `npm run build` then I get 

```

> front@0.1.0 build /Users/ozan/repos/piaf/src/piaf/front
> vue-cli-service build --dest '../static/front' "package.json"

sh: vue-cli-service: command not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! front@0.1.0 build: `vue-cli-service build --dest '../static/front' "package.json"`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the front@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/###/.npm/_logs/2020-06-18T06_41_17_498Z-debug.log
```
Anyhow, I was able to finish installation somehow via Python and Docker and then TemplateNotFound error shows up when I try to launch the app. 

Thanks,

Ozan

**Comment by guillim** [comment]
Thanks for your issue. One thing you can do is install [vue/cli](https://cli.vuejs.org/) globally on your computer by typing `npm install -g @vue/cli`

This should do the trick. 

Note :  if you don't want to do that, you can switch to the docker implementation.

Please try this and let me know if it works. About the Docker problem, I'll have to look deeper since it works on my machine

**Comment by oersoy1** [comment]
Thanks, that did not work.  Received all kinds of npm deprecated warnings and finally 

```
npm install -g @vue/cli
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules
npm WARN jscodeshift@0.9.0 requires a peer of @babel/preset-env@^7.1.6 but none is installed. You must install peer dependencies yourself.

npm ERR! code EACCES
npm ERR! syscall access
npm ERR! path /usr/local/lib/node_modules
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
npm ERR!  [Error: EACCES: permission denied, access '/usr/local/lib/node_modules'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.
```
Then I thought this was a permission issue and ran it as sudo, similar situation and then the front end does not work.  I will try to re-install via  Docker and report but this seems like a dead-end for me.

**Comment by guillim** [comment]
Let's come back to **docker installation**. I just tried installing Piaf from scratch again, and it works on my machine. So maybe there is something I don't explain right in the README.md ? 
Can you tell me what log error are you seeing ?


Note: don't forget the line ```cp .env-example .env``` otherwise, you'll see some log error like 

> django.core.exceptions.ImproperlyConfigured: settings.DATABASES is improperly configured. Please supply the ENGINE value. Check settings documentation for more details.

**Comment by guillim** [comment]
@oersoy1 did you manage to install and run Piaf through Docker ?

**Comment by arunzz** [comment]
Without docker, the step make build-statics fails with below error
sh: 1: vue-cli-service: not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! front@0.1.0 build: `vue-cli-service build --dest '../static/front'`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the front@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

I tried npm install -g @vue/cli too

**Comment by guillim** [comment]
I will have a look ASAP, thanks for your feeedback

**Comment by guillim** [comment]
Hello,
Sorry for the delay. 
- I added in the prerequisite the VueCli  
- I modified the script for `make build-statics` in order to avoid the missing static folder.
Is it working now @oersoy1 and @arunzz ?

**Comment by mathrb** [comment]
Hello,

I just cloned the repository, here are the issues I came across:
* Faker in requirements is 0.8.8 whereas another dependency is requesting 0.9.1, pretty straightforward to fix
* Login page displays correctly, after logging in, comes the next issue
* TemplateDoesNotExist at /app/ , for this one, I tried make build-statics (had to manually create the static folder though), but this issue persists

This is the kind of stack displayed in the browser:
`

Request Method: | GET
-- | --
http://localhost:8000/app/
2.1
TemplateDoesNotExist
front/index.html
/src/venv/lib/python3.6/site-packages/django/template/loader.py in select_template, line 47
/src/venv/bin/python3
3.6.13
['/src/src',  '/src',  '/',  '/src/venv/bin',  '/usr/local/lib/python36.zip',  '/usr/local/lib/python3.6',  '/usr/local/lib/python3.6/lib-dynload',  '/src/venv/lib/python3.6/site-packages']
mer, 17 Fév 2021 14:26:48 +0000

`

**Comment by mathrb** [comment]
Quick update: Actually it works, it's just taking a very long time to build resources. The web server is up before the static finishes the build. So wait for: webpack_1   | --> build => bundle finished

**Comment by guillim** [comment]
I updated most packages today. You shouldn't see any issues previously mentioned. Feel free to re-open this issue if it doesn't fix your problem
