### ISSUE TITLE
how to run in win10?

### ISSUE THREAD

**Issue by ScottishFold007** [etalab/piaf#30]
Hello! I tried to install piaf on docker, but had problems actually running it, I guess it's a path problem - the default paths here are for linux systems，I'd like to ask you how to run it properly on Win10, thanks!
Here is a screenshot of the error reported by docker on Win10：
![image](https://user-images.githubusercontent.com/36957508/108479409-a90e9000-72d0-11eb-847a-f8337074b858.png)
![image](https://user-images.githubusercontent.com/36957508/108479434-af9d0780-72d0-11eb-99e0-677458c3dc2c.png)
![image](https://user-images.githubusercontent.com/36957508/108479450-b75cac00-72d0-11eb-821d-2936ec2ecfe6.png)
![image](https://user-images.githubusercontent.com/36957508/108479475-be83ba00-72d0-11eb-8d1a-bd53ef1cf4da.png)

**Comment by guillim** [comment]
Did you find out ?

**Comment by guillim** [comment]
Please see issue #31 for more info on windows topics. Another user had a similar issue
