### ISSUE TITLE
Error when importing articles to be annotated

### ISSUE THREAD

**Issue by schmarion** [etalab/piaf#42]
Hi there,

When I try to import the example article for annotation on the /app/domain page, I get the following error:

> Environment:
>
>
>Request Method: POST
>Request URL: http://127.0.0.1:8000/app/admin/dataset
>
> 
> Django Version: 2.1
> Python Version: 3.8.5
> Installed Applications:
> ['django.contrib.admin',
>  'django.contrib.auth',
>  'django.contrib.contenttypes',
>  'django.contrib.sessions',
>  'django.contrib.messages',
>  'django.contrib.staticfiles',
>  'server.apps.ServerConfig',
>  'api.apps.ApiConfig',
>  'widget_tweaks',
>  'rest_framework',
>  'django_filters',
>  'polymorphic',
>  'anymail',
>  'piaf',
>  'account']
> Installed Middleware:
> ('whitenoise.middleware.WhiteNoiseMiddleware',
>  'django.middleware.security.SecurityMiddleware',
>  'django.contrib.sessions.middleware.SessionMiddleware',
>  'django.middleware.common.CommonMiddleware',
>  'django.middleware.csrf.CsrfViewMiddleware',
>  'django.contrib.auth.middleware.AuthenticationMiddleware',
>  'django.contrib.messages.middleware.MessageMiddleware',
>  'django.middleware.clickjacking.XFrameOptionsMiddleware',
>  'applicationinsights.django.ApplicationInsightsMiddleware')
> 
> 
> 
> Traceback:
> 
> File "/mnt/c/Users/sch-m/Documents/Extractive_QA/piaf/piaf/piaf_env/lib/python3.8/site-packages/django/db/backends/utils.py" in _execute
>   85.                 return self.cursor.execute(sql, params)
> 
> File "/mnt/c/Users/sch-m/Documents/Extractive_QA/piaf/piaf/piaf_env/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py" in execute
>   296.         return Database.Cursor.execute(self, query, params)
> 
> The above exception (no such table: main.piaf_article__old) was the direct cause of the following exception:
> 
> File "/mnt/c/Users/sch-m/Documents/Extractive_QA/piaf/piaf/piaf_env/lib/python3.8/site-packages/django/core/handlers/exception.py" in inner
>   34.             response = get_response(request)
> 
> File "/mnt/c/Users/sch-m/Documents/Extractive_QA/piaf/piaf/piaf_env/lib/python3.8/site-packages/django/core/handlers/base.py" in _get_response
>   126.                 response = self.process_exception_by_middleware(e, request)
> 
> File "/mnt/c/Users/sch-m/Documents/Extractive_QA/piaf/piaf/piaf_env/lib/python3.8/site-packages/django/core/handlers/base.py" in _get_response
>   124.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)
> 
> File "/mnt/c/Users/sch-m/Documents/Extractive_QA/piaf/piaf/piaf_env/lib/python3.8/site-packages/django/views/generic/base.py" in view
>   68.             return self.dispatch(request, *args, **kwargs)
> 
> File "/mnt/c/Users/sch-m/Documents/Extractive_QA/piaf/piaf/piaf_env/lib/python3.8/site-packages/django/contrib/auth/mixins.py" in dispatch
>   109.         return super().dispatch(request, *args, **kwargs)
> 
> File "/mnt/c/Users/sch-m/Documents/Extractive_QA/piaf/piaf/piaf_env/lib/python3.8/site-packages/django/views/generic/base.py" in dispatch
>   88.         return handler(request, *args, **kwargs)
> 
> File "/mnt/c/Users/sch-m/Documents/Extractive_QA/piaf/piaf/src/piaf/views.py" in post
>   84.                 paragraph.save()
> 
> File "/mnt/c/Users/sch-m/Documents/Extractive_QA/piaf/piaf/piaf_env/lib/python3.8/site-packages/django/db/models/base.py" in save
>   716.         self.save_base(using=using, force_insert=force_insert,
> 
> File "/mnt/c/Users/sch-m/Documents/Extractive_QA/piaf/piaf/piaf_env/lib/python3.8/site-packages/django/db/models/base.py" in save_base
>   747.             updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
> 
> File "/mnt/c/Users/sch-m/Documents/Extractive_QA/piaf/piaf/piaf_env/lib/python3.8/site-packages/django/db/models/base.py" in _save_table
>   830.             result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
> 
> File "/mnt/c/Users/sch-m/Documents/Extractive_QA/piaf/piaf/piaf_env/lib/python3.8/site-packages/django/db/models/base.py" in _do_insert
>   867.         return manager._insert([self], fields=fields, return_id=update_pk,
> 
> File "/mnt/c/Users/sch-m/Documents/Extractive_QA/piaf/piaf/piaf_env/lib/python3.8/site-packages/django/db/models/manager.py" in manager_method
>   82.                 return getattr(self.get_queryset(), name)(*args, **kwargs)
> 
> File "/mnt/c/Users/sch-m/Documents/Extractive_QA/piaf/piaf/piaf_env/lib/python3.8/site-packages/django/db/models/query.py" in _insert
>   1133.         return query.get_compiler(using=using).execute_sql(return_id)
> 
> File "/mnt/c/Users/sch-m/Documents/Extractive_QA/piaf/piaf/piaf_env/lib/python3.8/site-packages/django/db/models/sql/compiler.py" in execute_sql
>   1285.                 cursor.execute(sql, params)
> 
> File "/mnt/c/Users/sch-m/Documents/Extractive_QA/piaf/piaf/piaf_env/lib/python3.8/site-packages/django/db/backends/utils.py" in execute
>   100.             return super().execute(sql, params)
> 
> File "/mnt/c/Users/sch-m/Documents/Extractive_QA/piaf/piaf/piaf_env/lib/python3.8/site-packages/django/db/backends/utils.py" in execute
>   68.         return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
> 
> File "/mnt/c/Users/sch-m/Documents/Extractive_QA/piaf/piaf/piaf_env/lib/python3.8/site-packages/django/db/backends/utils.py" in _execute_with_wrappers
>   77.         return executor(sql, params, many, context)
> 
> File "/mnt/c/Users/sch-m/Documents/Extractive_QA/piaf/piaf/piaf_env/lib/python3.8/site-packages/django/db/backends/utils.py" in _execute
>   85.                 return self.cursor.execute(sql, params)
> 
> File "/mnt/c/Users/sch-m/Documents/Extractive_QA/piaf/piaf/piaf_env/lib/python3.8/site-packages/django/db/utils.py" in __exit__
>   89.                 raise dj_exc_value.with_traceback(traceback) from exc_value
> 
> File "/mnt/c/Users/sch-m/Documents/Extractive_QA/piaf/piaf/piaf_env/lib/python3.8/site-packages/django/db/backends/utils.py" in _execute
>   85.                 return self.cursor.execute(sql, params)
> 
> File "/mnt/c/Users/sch-m/Documents/Extractive_QA/piaf/piaf/piaf_env/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py" in execute
>   296.         return Database.Cursor.execute(self, query, params)
> 
> Exception Type: OperationalError at /app/admin/dataset
> Exception Value: no such table: main.piaf_article__old

I made a local installation on Ubuntu 20.04 (wsl2) without Docker.

Do you know how I can solve this problem?

Thanks a lot for your help

Marion

**Comment by guillim** [comment]
Ok. I tried to recreate your issue twice (using docker) and couldn't re-create the issue. My guess is that it is related to your linux env. 
Could you try with docker to make sure it works fine on your side as well ?

**Comment by guillim** [comment]
Ok. I tried to recreate your issue twice (using docker) and couldn't re-create the issue. My guess is that it is related to your linux env. 
Could you try with docker to make sure it works fine on your side as well ?

**Comment by schmarion** [comment]
Hi, I also have a problem when I try to do the `make up` command during the Docker installation :

Here is an extract of the logs : 

> [...]
> django_1    | Database unavailable on attempt 60/60: could not translate host name "postgres" to address: Name or service not known
> django_1    | Database unavailable
> [...]
> django_1    | Database unavailable on attempt 60/60: could not translate host name "postgres" to address: Name or service not known
> django_1    | Database unavailable
> [...]
> postgres_1  | chmod: changing permissions of '/var/lib/postgres/data': Operation not permitted
> [...]
> django_1    | Database unavailable on attempt 60/60: could not translate host name "postgres" to address: Name or service not known
> django_1    | Database unavailable
> django_1    | Installing dependencies
> [...]
> django_1    | Collecting static files
> postgres_1  | The files belonging to this database system will be owned by user "postgres".
> postgres_1  | This user must also own the server process.
> postgres_1  |
> postgres_1  | The database cluster will be initialized with locale "en_US.utf8".
> postgres_1  | The default database encoding has accordingly been set to "UTF8".
> postgres_1  | The default text search configuration will be set to "english".
> postgres_1  |
> postgres_1  | Data page checksums are disabled.
> postgres_1  |
> postgres_1  | fixing permissions on existing directory /var/lib/postgres/data ... initdb: could not change permissions of directory "/var/lib/postgres/data": Operation not permitted
> webpack_1   | Starting npm run...  with WEBPACK_ENVIRONMENT_PRODUCTION = True
> webpack_1   | --> building bundle for production
> django_1    |
> django_1    | 82 static files copied to '/src/src/staticfiles', 154 unmodified, 597 post-processed.
> django_1    | Initializing database
> piaf_postgres_1 exited with code 1
> webpack_1   |
> webpack_1   | > front@0.1.0 build /src/src/piaf/front
> webpack_1   | > vue-cli-service build --dest '../static/front'
> webpack_1   |
> webpack_1   |
> webpack_1   | -  Building for production...
> webpack_1   |  WARN  A new version of sass-loader is available. Please upgrade for best experience.
> webpack_1   | Browserslist: caniuse-lite is outdated. Please run:
> webpack_1   | npx browserslist@latest --update-db
> webpack_1   |  WARNING  Compiled with 2 warnings15:58:23
> webpack_1   |
> webpack_1   |  warning
> webpack_1   |
> webpack_1   | asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
> webpack_1   | This can impact web performance.
> webpack_1   | Assets:
> webpack_1   |   chunk-vendors.css (369 KiB)
> webpack_1   |   chunk-vendors.js (358 KiB)
> webpack_1   |
> webpack_1   |  warning
> webpack_1   |
> webpack_1   | entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
> webpack_1   | Entrypoints:
> webpack_1   |   app (760 KiB)
> webpack_1   |       chunk-vendors.css
> webpack_1   |       chunk-vendors.js
> webpack_1   |       app.css
> webpack_1   |       app.js
> webpack_1   |
> webpack_1   |
> webpack_1   |   File                                  Size               Gzipped
> webpack_1   |
> webpack_1   |   ../static/front/chunk-vendors.js      358.15 KiB         114.76 KiB
> webpack_1   |   ../static/front/chunk-7eb131ec.js     67.25 KiB          16.83 KiB
> webpack_1   |   ../static/front/app.js                31.51 KiB          8.89 KiB
> webpack_1   |   ../static/front/chunk-9e395612.js     19.72 KiB          4.68 KiB
> webpack_1   |   ../static/front/chunk-03435343.js     18.56 KiB          4.18 KiB
> webpack_1   |   ../static/front/chunk-2d21f87a.js     11.41 KiB          3.42 KiB
> webpack_1   |   ../static/front/chunk-7f2448df.js     10.94 KiB          3.73 KiB
> webpack_1   |   ../static/front/chunk-ddf14682.js     4.09 KiB           1.75 KiB
> webpack_1   |   ../static/front/chunk-2d0bd197.js     3.37 KiB           1.50 KiB
> webpack_1   |   ../static/front/chunk-2d216420.js     2.18 KiB           1.08 KiB
> webpack_1   |   ../static/front/chunk-2d0babff.js     1.78 KiB           0.99 KiB
> webpack_1   |   ../static/front/chunk-2d0cbe87.js     0.73 KiB           0.48 KiB
> webpack_1   |   ../static/front/chunk-vendors.css     368.82 KiB         42.45 KiB
> webpack_1   |   ../static/front/chunk-7eb131ec.css    49.14 KiB          6.56 KiB
> webpack_1   |   ../static/front/chunk-7f2448df.css    7.46 KiB           1.78 KiB
> webpack_1   |   ../static/front/chunk-9e395612.css    2.74 KiB           0.80 KiB
> webpack_1   |   ../static/front/chunk-ddf14682.css    1.66 KiB           0.62 KiB
> webpack_1   |   ../static/front/app.css               1.38 KiB           0.64 KiB
> webpack_1   |   ../static/front/chunk-03435343.css    0.99 KiB           0.37 KiB
> webpack_1   |
> webpack_1   |   Images and other types of assets omitted.
> webpack_1   |
> webpack_1   |  DONE  Build complete. The ../static/front directory is ready to be deployed.
> webpack_1   |  INFO  Check out deployment instructions at https://cli.vuejs.org/guide/deployment.html
> webpack_1   |
> webpack_1   | --> build => bundle finished
> piaf_webpack_1 exited with code 0
> [...]
> django_1    | Database unavailable on attempt 60/60: could not translate host name "postgres" to address: Temporary failure in name resolution
> django_1    | Database unavailable
> piaf_django_1 exited with code 1

**Comment by guillim** [comment]
It's another issue you have here : probably related to Postgres according to the logs. Can you create a /src/db folder with all sufficient privileges for Postgres to write and read from it ? By default, the database will be stored into this folder.

**Comment by schmarion** [comment]
Ok so I checked privileges and I have the rights to read/write/execute in this directory. 
However, I used your command as root (docker problems) so I changed this and now I have this issue that seems quite similar: 

`make up`

> if [[ ! -d "src/db" ]]; then \
>         mkdir src/db; \
> fi; \
> 'docker-compose' up
> Starting piaf_django_1     ... done
> Starting piaf_webpack_1    ... done
> Recreating piaf_postgres_1 ... done
> Attaching to piaf_webpack_1, piaf_django_1, piaf_postgres_1
> django_1    | Installing dependencies
> webpack_1   | Installing dependencies
> postgres_1  | chmod: changing permissions of '/var/lib/postgres/data': Operation not permitted
> postgres_1  | The files belonging to this database system will be owned by user "postgres".
> postgres_1  | This user must also own the server process.
> postgres_1  |
> postgres_1  | The database cluster will be initialized with locale "en_US.utf8".
> postgres_1  | The default database encoding has accordingly been set to "UTF8".
> postgres_1  | The default text search configuration will be set to "english".
> postgres_1  |
> postgres_1  | Data page checksums are disabled.
> postgres_1  |
> postgres_1  | initdb: could not change permissions of directory "/var/lib/postgres/data": Operation not permitted
> postgres_1  | fixing permissions on existing directory /var/lib/postgres/data ... piaf_postgres_1 exited with code 1
> django_1    | Requirement already satisfied: apache-libcloud==2.4.0 in /src/venv/lib/python3.6/site-packages (from -r /src/tools/../requirements.txt (line 1)) (2.4.0)
> django_1    | Requirement already satisfied: applicationinsights==0.11.7 in /src/venv/lib/python3.6/site-packages (from -r /src/tools/../requirements.txt (line 2)) (0.11.7)
> django_1    | Requirement already satisfied: coverage==4.5.3 in /src/venv/lib/python3.6/site-packages (from -r /src/tools/../requirements.txt (line 3)) (4.5.3)
> django_1    | Requirement already satisfied: dj-database-url==0.5.0 in /src/venv/lib/python3.6/site-packages (from -r /src/tools/../requirements.txt (line 4)) (0.5.0)
> django_1    | Requirement already satisfied: Django==2.1 in /src/venv/lib/python3.6/site-packages (from -r /src/tools/../requirements.txt (line 5)) (2.1)
> django_1    | Requirement already satisfied: django-cloud-browser==0.5.0 in /src/venv/lib/python3.6/site-packages (from -r /src/tools/../requirements.txt (line 6)) (0.5.0)
> django_1    | Requirement already satisfied: django-filter==2.0.0 in /src/venv/lib/python3.6/site-packages (from -r /src/tools/../requirements.txt (line 7)) (2.0.0)
> django_1    | Requirement already satisfied: django-heroku==0.3.1 in /src/venv/lib/python3.6/site-packages (from -r /src/tools/../requirements.txt (line 8)) (0.3.1)
> django_1    | Requirement already satisfied: django-widget-tweaks==1.4.2 in /src/venv/lib/python3.6/site-packages (from -r /src/tools/../requirements.txt (line 9)) (1.4.2)
> django_1    | Requirement already satisfied: django-polymorphic==2.0.3 in /src/venv/lib/python3.6/site-packages (from -r /src/tools/../requirements.txt (line 10)) (2.0.3)
> django_1    | Requirement already satisfied: django-rest-polymorphic==0.1.8 in /src/venv/lib/python3.6/site-packages (from -r /src/tools/../requirements.txt (line 11)) (0.1.8)
> django_1    | Requirement already satisfied: djangorestframework==3.8.2 in /src/venv/lib/python3.6/site-packages (from -r /src/tools/../requirements.txt (line 12)) (3.8.2)
> django_1    | Requirement already satisfied: djangorestframework-csv==2.1.0 in /src/venv/lib/python3.6/site-packages (from -r /src/tools/../requirements.txt (line 13)) (2.1.0)
> django_1    | Requirement already satisfied: djangorestframework-filters==0.10.2 in /src/venv/lib/python3.6/site-packages (from -r /src/tools/../requirements.txt (line 14)) (0.10.2)
> django_1    | Requirement already satisfied: environs==4.1.0 in /src/venv/lib/python3.6/site-packages (from -r /src/tools/../requirements.txt (line 15)) (4.1.0)
> django_1    | Requirement already satisfied: djangorestframework-xml==1.4.0 in /src/venv/lib/python3.6/site-packages (from -r /src/tools/../requirements.txt (line 16)) (1.4.0)
> django_1    | Requirement already satisfied: Faker>=0.8 in /src/venv/lib/python3.6/site-packages (from -r /src/tools/../requirements.txt (line 17)) (0.9.1)
> django_1    | Requirement already satisfied: flake8==3.6.0 in /src/venv/lib/python3.6/site-packages (from -r /src/tools/../requirements.txt (line 18)) (3.6.0)
> django_1    | Requirement already satisfied: furl==2.0.0 in /src/venv/lib/python3.6/site-packages (from -r /src/tools/../requirements.txt (line 19)) (2.0.0)
> django_1    | Requirement already satisfied: gunicorn==19.9.0 in /src/venv/lib/python3.6/site-packages (from -r /src/tools/../requirements.txt (line 20)) (19.9.0)
> django_1    | Requirement already satisfied: lockfile==0.12.2 in /src/venv/lib/python3.6/site-packages (from -r /src/tools/../requirements.txt (line 21)) (0.12.2)
> django_1    | Requirement already satisfied: mixer==6.1.3 in /src/venv/lib/python3.6/site-packages (from -r /src/tools/../requirements.txt (line 22)) (6.1.3)
> django_1    | Requirement already satisfied: model-mommy==1.6.0 in /src/venv/lib/python3.6/site-packages (from -r /src/tools/../requirements.txt (line 23)) (1.6.0)
> django_1    | Requirement already satisfied: psycopg2-binary==2.7.7 in /src/venv/lib/python3.6/site-packages (from -r /src/tools/../requirements.txt (line 24)) (2.7.7)
> django_1    | Requirement already satisfied: python-dateutil==2.7.3 in /src/venv/lib/python3.6/site-packages (from -r /src/tools/../requirements.txt (line 25)) (2.7.3)
> django_1    | Requirement already satisfied: pytz==2018.4 in /src/venv/lib/python3.6/site-packages (from -r /src/tools/../requirements.txt (line 26)) (2018.4)
> django_1    | Requirement already satisfied: requests==2.21.0 in /src/venv/lib/python3.6/site-packages (from -r /src/tools/../requirements.txt (line 27)) (2.21.0)
> django_1    | Requirement already satisfied: six==1.11.0 in /src/venv/lib/python3.6/site-packages (from -r /src/tools/../requirements.txt (line 28)) (1.11.0)
> django_1    | Requirement already satisfied: seqeval==0.0.6 in /src/venv/lib/python3.6/site-packages (from -r /src/tools/../requirements.txt (line 29)) (0.0.6)
> django_1    | Requirement already satisfied: text-unidecode==1.2 in /src/venv/lib/python3.6/site-packages (from -r /src/tools/../requirements.txt (line 30)) (1.2)
> django_1    | Requirement already satisfied: tornado==5.0.2 in /src/venv/lib/python3.6/site-packages (from -r /src/tools/../requirements.txt (line 31)) (5.0.2)
> django_1    | Requirement already satisfied: unittest-xml-reporting==2.5.1 in /src/venv/lib/python3.6/site-packages (from -r /src/tools/../requirements.txt (line 32)) (2.5.1)
> django_1    | Requirement already satisfied: vcrpy==2.0.1 in /src/venv/lib/python3.6/site-packages (from -r /src/tools/../requirements.txt (line 33)) (2.0.1)
> django_1    | Requirement already satisfied: vcrpy-unittest==0.1.7 in /src/venv/lib/python3.6/site-packages (from -r /src/tools/../requirements.txt (line 34)) (0.1.7)
> django_1    | Requirement already satisfied: django-anymail==7.0.0 in /src/venv/lib/python3.6/site-packages (from -r /src/tools/../requirements.txt (line 35)) (7.0.0)
> django_1    | Requirement already satisfied: psycopg2 in /src/venv/lib/python3.6/site-packages (from django-heroku==0.3.1->-r /src/tools/../requirements.txt (line 8)) (2.9.1)
> django_1    | Requirement already satisfied: whitenoise in /src/venv/lib/python3.6/site-packages (from django-heroku==0.3.1->-r /src/tools/../requirements.txt (line 8)) (5.3.0)
> django_1    | Requirement already satisfied: unicodecsv in /src/venv/lib/python3.6/site-packages (from djangorestframework-csv==2.1.0->-r /src/tools/../requirements.txt (line 13)) (0.14.1)
> django_1    | Requirement already satisfied: marshmallow>=2.7.0 in /src/venv/lib/python3.6/site-packages (from environs==4.1.0->-r /src/tools/../requirements.txt (line 15)) (3.13.0)
> django_1    | Requirement already satisfied: python-dotenv in /src/venv/lib/python3.6/site-packages (from environs==4.1.0->-r /src/tools/../requirements.txt (line 15)) (0.19.1)
> django_1    | Requirement already satisfied: defusedxml>=0.3 in /src/venv/lib/python3.6/site-packages (from djangorestframework-xml==1.4.0->-r /src/tools/../requirements.txt (line 16)) (0.7.1)
> django_1    | Requirement already satisfied: pyflakes<2.1.0,>=2.0.0 in /src/venv/lib/python3.6/site-packages (from flake8==3.6.0->-r /src/tools/../requirements.txt (line 18)) (2.0.0)
> django_1    | Requirement already satisfied: pycodestyle<2.5.0,>=2.4.0 in /src/venv/lib/python3.6/site-packages (from flake8==3.6.0->-r /src/tools/../requirements.txt (line 18)) (2.4.0)
> django_1    | Requirement already satisfied: setuptools>=30 in /src/venv/lib/python3.6/site-packages (from flake8==3.6.0->-r /src/tools/../requirements.txt (line 18)) (58.2.0)
> django_1    | Requirement already satisfied: mccabe<0.7.0,>=0.6.0 in /src/venv/lib/python3.6/site-packages (from flake8==3.6.0->-r /src/tools/../requirements.txt (line 18)) (0.6.1)
> django_1    | Requirement already satisfied: orderedmultidict>=1.0 in /src/venv/lib/python3.6/site-packages (from furl==2.0.0->-r /src/tools/../requirements.txt (line 19)) (1.0.1)
> django_1    | Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /src/venv/lib/python3.6/site-packages (from requests==2.21.0->-r /src/tools/../requirements.txt (line 27)) (3.0.4)
> django_1    | Requirement already satisfied: idna<2.9,>=2.5 in /src/venv/lib/python3.6/site-packages (from requests==2.21.0->-r /src/tools/../requirements.txt (line 27)) (2.8)
> django_1    | Requirement already satisfied: certifi>=2017.4.17 in /src/venv/lib/python3.6/site-packages (from requests==2.21.0->-r /src/tools/../requirements.txt (line 27)) (2021.10.8)
> django_1    | Requirement already satisfied: urllib3<1.25,>=1.21.1 in /src/venv/lib/python3.6/site-packages (from requests==2.21.0->-r /src/tools/../requirements.txt (line 27)) (1.24.3)
> django_1    | Requirement already satisfied: numpy>=1.14.0 in /src/venv/lib/python3.6/site-packages (from seqeval==0.0.6->-r /src/tools/../requirements.txt (line 29)) (1.19.5)
> django_1    | Requirement already satisfied: yarl in /src/venv/lib/python3.6/site-packages (from vcrpy==2.0.1->-r /src/tools/../requirements.txt (line 33)) (1.7.0)
> django_1    | Requirement already satisfied: PyYAML in /src/venv/lib/python3.6/site-packages (from vcrpy==2.0.1->-r /src/tools/../requirements.txt (line 33)) (6.0)
> django_1    | Requirement already satisfied: wrapt in /src/venv/lib/python3.6/site-packages (from vcrpy==2.0.1->-r /src/tools/../requirements.txt (line 33)) (1.13.2)
> django_1    | Requirement already satisfied: multidict>=4.0 in /src/venv/lib/python3.6/site-packages (from yarl->vcrpy==2.0.1->-r /src/tools/../requirements.txt (line 33)) (5.2.0)
> django_1    | Requirement already satisfied: typing-extensions>=3.7.4 in /src/venv/lib/python3.6/site-packages (from yarl->vcrpy==2.0.1->-r /src/tools/../requirements.txt (line 33)) (3.10.0.2)
> django_1    | Collecting static files
> django_1    |
> django_1    | 154 static files copied to '/src/src/staticfiles', 482 post-processed.
> django_1    | Initializing database
> webpack_1   | npm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EAI_AGAIN: request to https://registry.npmjs.org/vue-loader failed, reason: getaddrinfo EAI_AGAIN registry.npmjs.org:443
> webpack_1   | npm WARN registry Using stale data from https://registry.npmjs.org/ due to a request error during revalidation.
> webpack_1   |
> webpack_1   | > yorkie@2.0.0 install /src/src/piaf/front/node_modules/yorkie
> webpack_1   | > node bin/install.js
> webpack_1   |
> webpack_1   | setting up Git hooks
> webpack_1   | can't find .git directory, skipping Git hooks installation
> webpack_1   |
> webpack_1   | > core-js@2.6.12 postinstall /src/src/piaf/front/node_modules/core-js
> webpack_1   | > node -e "try{require('./postinstall')}catch(e){}"
> webpack_1   |
> webpack_1   | Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!
> webpack_1   |
> webpack_1   | The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> webpack_1   | > https://opencollective.com/core-js
> webpack_1   | > https://www.patreon.com/zloirock
> webpack_1   |
> webpack_1   | Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)
> webpack_1   |
> webpack_1   |
> webpack_1   | > ejs@2.7.4 postinstall /src/src/piaf/front/node_modules/ejs
> webpack_1   | > node ./postinstall.js
> webpack_1   |
> webpack_1   | Thank you for installing EJS: built with the Jake JavaScript build tool (https://jakejs.com/)
> webpack_1   |
> webpack_1   | npm WARN notsup Unsupported engine for chalk@4.1.2: wanted: {"node":">=10"} (current: {"node":"8.17.0","npm":"6.13.4"})
> webpack_1   | npm WARN notsup Not compatible with your version of node/npm: chalk@4.1.2
> webpack_1   | npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/webpack-dev-server/node_modules/fsevents):
> webpack_1   | npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
> webpack_1   | npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
> webpack_1   | npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
> webpack_1   | npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
> webpack_1   | npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
> webpack_1   |
> webpack_1   | added 1416 packages from 1056 contributors in 330.8s
> webpack_1   |
> webpack_1   | 66 packages are looking for funding
> webpack_1   |   run `npm fund` for details
> webpack_1   |
> webpack_1   | Starting npm run...  with WEBPACK_ENVIRONMENT_PRODUCTION = True
> webpack_1   | --> building bundle for production
> webpack_1   |
> webpack_1   | > front@0.1.0 build /src/src/piaf/front
> webpack_1   | > vue-cli-service build --dest '../static/front'
> webpack_1   |
> webpack_1   |
> webpack_1   | -  Building for production...
> webpack_1   |  WARN  A new version of sass-loader is available. Please upgrade for best experience.
> webpack_1   | Browserslist: caniuse-lite is outdated. Please run:
> webpack_1   | npx browserslist@latest --update-db
> webpack_1   |  WARNING  Compiled with 2 warnings12:18:14
> webpack_1   |
> webpack_1   |  warning
> webpack_1   |
> webpack_1   | asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
> webpack_1   | This can impact web performance.
> webpack_1   | Assets:
> webpack_1   |   chunk-vendors.css (369 KiB)
> webpack_1   |   chunk-vendors.js (358 KiB)
> webpack_1   |
> webpack_1   |  warning
> webpack_1   |
> webpack_1   | entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
> webpack_1   | Entrypoints:
> webpack_1   |   app (760 KiB)
> webpack_1   |       chunk-vendors.css
> webpack_1   |       chunk-vendors.js
> webpack_1   |       app.css
> webpack_1   |       app.js
> webpack_1   |
> webpack_1   |
> webpack_1   |   File                                  Size               Gzipped
> webpack_1   |
> webpack_1   |   ../static/front/chunk-vendors.js      358.15 KiB         114.76 KiB
> webpack_1   |   ../static/front/chunk-7eb131ec.js     67.25 KiB          16.83 KiB
> webpack_1   |   ../static/front/app.js                31.51 KiB          8.89 KiB
> webpack_1   |   ../static/front/chunk-9e395612.js     19.72 KiB          4.68 KiB
> webpack_1   |   ../static/front/chunk-03435343.js     18.56 KiB          4.18 KiB
> webpack_1   |   ../static/front/chunk-2d21f87a.js     11.41 KiB          3.42 KiB
> webpack_1   |   ../static/front/chunk-7f2448df.js     10.94 KiB          3.73 KiB
> webpack_1   |   ../static/front/chunk-ddf14682.js     4.09 KiB           1.75 KiB
> webpack_1   |   ../static/front/chunk-2d0bd197.js     3.37 KiB           1.50 KiB
> webpack_1   |   ../static/front/chunk-2d216420.js     2.18 KiB           1.08 KiB
> webpack_1   |   ../static/front/chunk-2d0babff.js     1.78 KiB           0.99 KiB
> webpack_1   |   ../static/front/chunk-2d0cbe87.js     0.73 KiB           0.48 KiB
> webpack_1   |   ../static/front/chunk-vendors.css     368.82 KiB         42.45 KiB
> webpack_1   |   ../static/front/chunk-7eb131ec.css    49.14 KiB          6.56 KiB
> webpack_1   |   ../static/front/chunk-7f2448df.css    7.46 KiB           1.78 KiB
> webpack_1   |   ../static/front/chunk-9e395612.css    2.74 KiB           0.80 KiB
> webpack_1   |   ../static/front/chunk-ddf14682.css    1.66 KiB           0.62 KiB
> webpack_1   |   ../static/front/app.css               1.38 KiB           0.64 KiB
> webpack_1   |   ../static/front/chunk-03435343.css    0.99 KiB           0.37 KiB
> webpack_1   |
> webpack_1   |   Images and other types of assets omitted.
> webpack_1   |
> webpack_1   |  DONE  Build complete. The ../static/front directory is ready to be deployed.
> webpack_1   |  INFO  Check out deployment instructions at https://cli.vuejs.org/guide/deployment.html
> webpack_1   |
> webpack_1   | --> build => bundle finished
> piaf_webpack_1 exited with code 0
> [...]
> django_1    | Database unavailable on attempt 60/60: could not translate host name "postgres" to address: Temporary failure in name resolution
> django_1    | Database unavailable
> piaf_django_1 exited with code 1

**Comment by guillim** [comment]
You still have a permission issue 
```bash
postgres_1 | chmod: changing permissions of '/var/lib/postgres/data': Operation not permitted
postgres_1 | The files belonging to this database system will be owned by user "postgres".
postgres_1 | This user must also own the server process.
```
Maybe not very clear but here it says your user "postgres" must have the writes on this folder `/var/lib/postgres/data`

I would suggest something this (didn't test, might need adjustment) :
if you don't have a postgres user yet, create it : `sudo useradd postgres`
Then make it owner of the folder  `sudo chown -R postgres /var/lib/postgres/data`
 `sudo chmod -R ug+rw /var/lib/postgres/data`

**Comment by schmarion** [comment]
Hi, thank you for your help. Unfortunetly these commands did not solve the problem, I have exactly the same errors. I see lot of others issues with postgres on wsl (1 and 2), I keep trying to solve this

**Comment by schmarion** [comment]
I finally solve this issue. In fact, when working on wsl into mounted volumes to share files between linux and windows distribution (`marion@DESKTOP:/mnt/c/Users/<path>/piaf`), there are known permissions problems with user "postgres". 
I just did the installation process at the root, without any mounted volume (`marion@DESKTOP:~/piaf`) and it worked just fine
