### ISSUE TITLE
User instructions

### ISSUE THREAD

**Issue by vinyll** [etalab/piaf#5]
Right now a "no message" banner appears when the user is starting.
We need a more user-friendly approach to give instructions.

Suggestions :
- https://pulsardev.github.io/vue-tour/
- https://plantain-00.github.io/tour-component/packages/vue/demo/

The interface should be clear to understand with very few (or no) instruction:

<img width="738" alt="Screenshot 2019-09-25 at 22 38 19" src="https://user-images.githubusercontent.com/145172/65637918-53ec2300-dfe5-11e9-899e-c3f15c52ceb7.png">

**Comment by guillim** [comment]
J'aime beaucoup Vue Tour

**Comment by guillim** [comment]
I think we can close this issue now that the onboarding is in place
