### ISSUE TITLE
Error 500 when debug = False

### ISSUE THREAD

**Issue by vinyll** [etalab/piaf#8]
switching to `debug=False` in app/app/settings.py throws an error 500.

**Comment by vinyll** [comment]
First hint: `ValueError: Missing staticfiles manifest entry for…`
Seems to be the static file folder that can't be found in production

**Comment by guillim** [comment]
which means we could simply check if we are running **npm build** in case we set **DEBUG=False** at least to begin with

**Comment by vinyll** [comment]
`npm run build` and `manage.py collectstatics` was not enough.
